### ISSUE TITLE
Can't discover virtual device

### ISSUE THREAD

**Issue by kljhbas** [aws-samples/aws-alexa-workshop#17]
I setup a virtual device named acedia_ratchet step by step according tutorials, when I test-shadow with $aws/things/acedia_ratchet/shadow/update, the shadow message always show "Hello from AWS IoT console". But I can bind device successfully.

    Then I go on until Step 9 DISCOVER SMART HOME DEVICES, I can't discover my device. I check tutorials and my workshop again, it seems all right.

    Can you give me some suggesttions to discovery device?

    Thanks!

**Comment by JoeShi** [comment]
Hi, Could you please check the Lambda log created in https://alexaworkshop.com/en/smart-home/7.create-lambda.html.

If you see the following error. 
```
TypeError: uuid is not a function","    at new AlexaResponse (/var/task/alexa/skills/smarthome/AlexaResponse.js:58:58)","
```

Please checkout the new code. This is due to an update to the `uuid` library. The library has update its usage. We have update the lambda code to fix this issue.

**Comment by JoeShi** [comment]
close, this issue has been fixed.
